### ISSUE TITLE
As a user, I want a form page to login.

### ISSUE THREAD

**Issue by surabhi8** [MiniDigitalBank/piggyBank#33]
Task 1: A navigation bar at the top of the page.
Task 2: A form for user to enter his details.
Task 3: A submit button to trigger next action.

**Comment by Paridhi815** [comment]
| Scenario | User should be allowed to enter his login details|
| --------|:--------|
| Given            | The user has already registered |
| When            | The user clicks on the login page |
| Then             | The user should be able to enter his login credentials  |
