### ISSUE TITLE
As a user, I want to login by giving my login credentials.  

### ISSUE THREAD

**Issue by surabhi8** [MiniDigitalBank/piggyBank#34]
Task 1: Authentication of user
Task 2: Use personalDetailsAPI
Task 3: Show personal details

**Comment by Paridhi815** [comment]
| Scenario | User should be allowed to enter his login details|
| --------|:--------|
| Given            | Then user has chosen to login |
| When            | The user fills the correct credentials |
| Then             | The user should be redirected to a page where he can see his personal details  |

**Comment by Paridhi815** [comment]
| Scenario |  User fills the login form incorrectly |
| --------|:--------|
| Given            | Then user has chosen to login |
| When            | The user fills the incorrect credentials |
| Then             | The user should be given an error message:Authentication Failed |
