### ISSUE TITLE
As a user, I want to view my account details after logging in. 

### ISSUE THREAD

**Issue by surabhi8** [MiniDigitalBank/piggyBank#35]

**Comment by Paridhi815** [comment]
| Scenario | Authenticated and Registered User has logged in|
| --------|:--------|
| Given            | The user has logged in |
| When            | The user gives correct credentials  |
| Then             | The user should be able to view all his personal details |

**Comment by anmol5varma** [comment]
Task 1: Get username from the session.
Task 2: Fetch the database using the username to get rest of the details.
Task 3: Create a model to make requests to the database.
Task 4: Use Vision library to render page dynamically by sending the data as a query to the template.
Task 5: The details should be displayed clearly and distinctly to the user without any confusion.
