### ISSUE TITLE
As a user, I want to update my password.

### ISSUE THREAD

**Issue by surabhi8** [MiniDigitalBank/piggyBank#36]
Tasks
- [ ] Create a form to enter current password and new password and make sure all fields are obscured
- [ ] Implement an API that verifies the current password and makes sure the new entered passwords are the same and that they fit certain acceptance criteria and updates password in database

**Comment by Paridhi815** [comment]
| Scenario | User wants to change his current password |
| --------|:--------|
| Given            |  A registered user has opted for changing his current password |
| When            | The user enters his current correct password as well as the new password twice|
| Then             | The user's password should get updated in the database and he should be able to login with the new password from the next time. |
